spring.application.name=UserService

server.port=${SERVER_PORT}
server.address=${SERVER_ADDRESS}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

#spring.liquibase.default-schema=auth
#spring.liquibase.default-schema=public
spring.liquibase.change-log=classpath:db/migrations/changelog.xml


spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
server.error.include-message=always

jwt.secret.access=${JWT_SECRET_ACCESS}
jwt.secret.refresh=${JWT_SECRET_REFRESH}
jwt.secret.auth.telegram=${JWT_SECRET_AUTH_TELEGRAM}
#security.jwt.expiration-time=100000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.consumer.group-id=auth_microservice
spring.kafka.consumer.auto-offset-reset=earliest

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile, email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=sub

telegram.bot.username=${TELEGRAM_BOT_USERNAME}
telegram.bot.token=${TELEGRAM_BOT_TOKEN}


telegram.bot.enabled=true

#springdoc.api-docs.path=/api-docs
#springdoc.swagger-ui.path=/swagger-ui

#http://localhost:8761/eureka/
#eureka.client.service-url.defaultZone=${EUREKA_DEFAULT_ZONE}
#eureka.instance.prefer-ip-address=true

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html




